### ISSUE TITLE
LLVM15 Checklist

### ISSUE THREAD

**Issue by thewilsonator** [ldc-developers/ldc#4042]
A List of things that need to be done to support LLVM15

[Opaque pointers:](https://llvm.org/docs/OpaquePointers.html)
- [ ] Remove use of [`getPointeeType`](https://github.com/ldc-developers/ldc/search?q=getPointeeType)
- [ ] Remove use of [`getPointerElementType`](https://github.com/ldc-developers/ldc/search?q=getPointerElementType)
- [ ] Rewok [`DtoLoad`](https://github.com/ldc-developers/ldc/search?q=DtoLoad) to not use `getPointerElementType`
- [ ] Rework [`DtoGep`](https://github.com/ldc-developers/ldc/search?q=DtoGep) (and friends) to not use `getPointerElementType`

[Pass Infrastructure](https://llvm.org/docs/NewPassManager.html)
- [ ] Move [our use of the Sanitiser Passes](https://github.com/ldc-developers/ldc/search?q=Sanitizer) to the [new pass structure](https://llvm.org/docs/NewPassManager.html)
- [ ] Move Our [custom passes](https://github.com/ldc-developers/ldc/tree/master/gen/passes) (gc2stack and friends) to the [new pass structure](https://llvm.org/docs/NewPassManager.html)
- [ ] https://github.com/ldc-developers/ldc/issues/3961

**Comment by thewilsonator** [comment]
Open PRs: 
- [ ] https://github.com/ldc-developers/ldc/pull/4022
- [ ] https://github.com/ldc-developers/ldc/pull/4038
- [ ] https://github.com/ldc-developers/ldc/pull/4039
- [ ] https://github.com/ldc-developers/ldc/pull/4040
- [ ] https://github.com/ldc-developers/ldc/pull/4041

**Comment by JohanEngelen** [comment]
For migrating to the new passmanager, I guess the best approach is to introduce a temporary cmdline flag that switches to the new passmanager, i.e. chooses a different code path where we create the new passmanager where we add sanitizers and our own special passes? Temporary, because at the start that new passmanager path does not have our custom passes until they have been migrated. This would enable testing both paths .

**Comment by thewilsonator** [comment]
How do submodule PRs work again?

**Comment by thewilsonator** [comment]
On the topic of updating the test suite to work with opaque pointers: any idea what the best way to do that is?

**Comment by JohanEngelen** [comment]
> On the topic of updating the test suite to work with opaque pointers: any idea what the best way to do that is?

FileCheck understands regexp, so we can do something like `{{(i8*|ptr)}}`

**Comment by JohanEngelen** [comment]
And if you want to check whether the test works with opaque pointers (without using LLVM15), you can use `--opaque-pointers`: https://d.godbolt.org/z/Kaeqxbhx6
